# This file was generated by GoReleaser. DO NOT EDIT.
cask "floop" do
  name "floop"
  desc "Behavior learning for AI agents"
  homepage "https://github.com/nvandessel/floop"
  version "0.18.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "floop"

  on_macos do
    on_intel do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-darwin-amd64.tar.gz"
      sha256 "3fab1df81c4d41eca3daf22441ce2599e0783fa381108e7d1d7e849daeb1b648"
    end
    on_arm do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-darwin-arm64.tar.gz"
      sha256 "87e29637ce0913bba4248896b1fc736b21393065500b4067ba58457ad215812a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-linux-amd64.tar.gz"
      sha256 "e09d7ded695e043c8e81d107a62d894ea2db0fec110efdfc37d2a6588918df93"
    end
    on_arm do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-linux-arm64.tar.gz"
      sha256 "7d33b71708064ee2844ce4e4aebec8a2c81cd793aa55d06bd8fdd5ceaad9bf92"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/floop"]
    end
  end

  # No zap stanza required
end
