# This file was generated by GoReleaser. DO NOT EDIT.
cask "floop" do
  name "floop"
  desc "Behavior learning for AI agents"
  homepage "https://github.com/nvandessel/floop"
  version "0.17.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "floop"

  on_macos do
    on_intel do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-darwin-amd64.tar.gz"
      sha256 "4e03c0c3cc1655e800ab35bd63a21bdfb8aee20825cd0befbe9c3c158f02f7e0"
    end
    on_arm do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-darwin-arm64.tar.gz"
      sha256 "f084f3fcbf8d1b2669da0210202592eb626c598c5dc8c35c0d4bb6b401757a12"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-linux-amd64.tar.gz"
      sha256 "9c94a9e477f1beb6e2afcbef17ebabc61340ecced4f44c5c176bf7a150cf14e9"
    end
    on_arm do
      url "https://github.com/nvandessel/floop/releases/download/v#{version}/floop-#{version}-linux-arm64.tar.gz"
      sha256 "5b4c81bebe16d8b9b170b0b3e2606b859630e04c8b67e505d313812d258f80b8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/floop"]
    end
  end

  # No zap stanza required
end
