# This file was generated by GoReleaser. DO NOT EDIT.
cask "frond" do
  name "frond"
  desc "Agent-first CLI for managing stacked PRs"
  homepage "https://github.com/nvandessel/frond"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frond"

  on_macos do
    on_intel do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_darwin_amd64.tar.gz"
      sha256 "4a3f8393d2dddf5ccef426e2b8227a07fbae5e2fd107ef0fad9eb3b097cb0771"
    end
    on_arm do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_darwin_arm64.tar.gz"
      sha256 "136d39e06e37c3f3cb6bbec0bcdb154a311488c2c25b078b0438ebb609a0043f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_linux_amd64.tar.gz"
      sha256 "8f061582740427a3bd2327e0c7e1ddecb2f097ca9ce61f5ed3c608aed804dad3"
    end
    on_arm do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_linux_arm64.tar.gz"
      sha256 "9ad3b6fc03b74d7255f4a53c1c2a998c63b7c6bc38a14afda36b92ef57f59803"
    end
  end

  # No zap stanza required
end
