# This file was generated by GoReleaser. DO NOT EDIT.
cask "frond" do
  name "frond"
  desc "Agent-first CLI for managing stacked PRs"
  homepage "https://github.com/nvandessel/frond"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frond"

  on_macos do
    on_intel do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_darwin_amd64.tar.gz"
      sha256 "43680eb27b40cf06df817015b0ddd53169a086ca52bda6ba6641a4af38aa8f0a"
    end
    on_arm do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_darwin_arm64.tar.gz"
      sha256 "e59323260dd15e57ed1d3bd084694a4d78ab93222d7233b3acb1a3bb4f64cb12"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_linux_amd64.tar.gz"
      sha256 "49df54890562632923b7078dd3923474d3e2b156b548c03c75b5f030fccf61c9"
    end
    on_arm do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_linux_arm64.tar.gz"
      sha256 "2956e73761fe45bd85eaff3a2d495db44f627728ecdc26928471f9e57912e448"
    end
  end

  # No zap stanza required
end
