# This file was generated by GoReleaser. DO NOT EDIT.
cask "frond" do
  name "frond"
  desc "Agent-first CLI for managing stacked PRs"
  homepage "https://github.com/nvandessel/frond"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frond"

  on_macos do
    on_intel do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_darwin_amd64.tar.gz"
      sha256 "3c3a6d36e46db58383a53555d302378494d2b3644526b885d29ed7ca81a790af"
    end
    on_arm do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_darwin_arm64.tar.gz"
      sha256 "9cf24feb509148e4825e58c469a9f20f016e71ebe25be9ec63fe98b36db5bbb8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_linux_amd64.tar.gz"
      sha256 "3d6c11a80309710174c6c7dadc3869205919b01022b2d463f191b113041e6036"
    end
    on_arm do
      url "https://github.com/nvandessel/frond/releases/download/v#{version}/frond_#{version}_linux_arm64.tar.gz"
      sha256 "340762affad8fc69d1b74a3b27a5c9cc4e6f6bff41439c0d4cc11251701a6bbd"
    end
  end

  # No zap stanza required
end
